<?php
$z[0]=Array("global","",12,44);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",169,197);
$z[1][4]['name']="cfg_mobileurl";
$z[2]=Array("global","",676,704);
$z[2][4]['name']="cfg_mobileurl";
$z[3]=Array("global","",850,882);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",976,1008);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1095,1120);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1212,1238);
$z[6][4]['name']="cfg_cmspath";

?>