<?php
$z[0]=Array("field","",14,37);
$z[0][4]['name']="id";
$z[1]=Array("field","",77,100);
$z[1][4]['name']="id";
$z[2]=Array("arclist","\r\n			<div class=\"item2 swiper-slide\">\r\n				<div class=\"item1_img\">\r\n					<a href='[field:arcurl/]'><img alt=\"\" src='[field:picname/] '/></a>\r\n				</div>\r\n				<div class=\"item1_content\">\r\n					<div class=\"item1_content_title\"><a href='[field:arcurl/]'>[field:title/]</a></div>\r\n					<div class=\"item1_content_text\">></div>\r\n				</div>\r\n			</div>\r\n			",218,630);
$z[2][4]['typt']="son";
$z[2][4]['limit']="0,20";
$z[2][4]['flag']="h";
$z[3]=Array("field","",812,835);
$z[3][4]['name']="id";
$z[4]=Array("field","",854,877);
$z[4][4]['name']="id";

?>