<?php
$z[0]=Array("global","",69,95);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",102,134);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",250,275);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n	      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n	      	",316,561);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>