<?php
$z[0]=Array("global","",284,310);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",317,349);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",465,490);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channel","\r\n	      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n	      	",531,793);
$z[3][4]['type']="top";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='top_menu_moveon_action'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";

?>