<?php
$z[0]=Array("global","",1946,1971);
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",2068,2100);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",2120,2152);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2173,2198);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",2373,2398);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("global","",2569,2594);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",2765,2790);
$z[6][4]['name']="cfg_cmsurl";

?>