<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[2]=array(0,1,1,'6L2v5Lu25a6a5Yi2');
$cfg_Cs[3]=array(0,1,1,'6Kej5Yaz5pa55qGI');
$cfg_Cs[4]=array(0,1,1,'5oiQ5Yqf5qGI5L6L');
$cfg_Cs[5]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[6]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[7]=array(1,1,1,'6KeG6aKR5Lya6K6u');
$cfg_Cs[8]=array(1,1,1,'5rWB5aqS5L2T6L2v5Lu2');
$cfg_Cs[9]=array(1,1,1,'6KeG6aKR5Lya6K6u5a6k');
?>